---
language: python
services: docker

jobs:
  include:
    - stage: ansible-lint
      name: Ansible Lint
      before_install:
        - pip3 install ansible-lint
      script:
        - ansible-lint tasks/main.yml || true
      after_script: true
    - stage: deploy
      name: Deploy on Ubuntu Focal
      env:
        - MOLECULE_DISTRO: ubuntu:20.04
    - stage: deployalt
      name: Deploy on Centos 8
      env:
        - MOLECULE_DISTRO: centos:8
    - stage: deployalt
      name: Deploy on Centos 7
      env:
        - MOLECULE_DISTRO: centos:7
    - stage: deployalt
      name: Deploy on Ubuntu Bionic
      env:
        - MOLECULE_DISTRO: ubuntu:18.04
    - stage: deployalt
      name: Deploy on Ubuntu Xenial
      env:
        - MOLECULE_DISTRO: ubuntu:16.04

env:
  global:
    - MOLECULE_NO_LOG: "false"

before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash

install:
  # Install test dependencies.
  - pip install molecule[docker] ansible-lint flake8 testinfra

before_script:
  - cd ../ && mv ansible-harden-sysctl juju4.harden_sysctl
  - cd juju4.harden_sysctl

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
