---
## https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

## FIXME! ansible sysctl module can't unset from sysctl.conf
- name: Absent
  when: harden_sysctl_distribution_remove is defined and harden_sysctl_distribution_remove
  block:
    - name: Container
      when: >
        - is_container
        - harden_sysctl_distribution_remove_containers is defined
        - harden_sysctl_distribution_remove_containers | bool
      block:
        - name: Harden sysctl config - remove (containers)
          ansible.builtin.lineinfile:
            name: /etc/sysctl.conf
            regexp: "^{{ item }}="
            state: absent
          with_items: "{{ harden_sysctl_distribution_remove_containers }}"
    - name: Harden sysctl config - remove
      ansible.builtin.lineinfile:
        name: /etc/sysctl.conf
        regexp: "^{{ item }}="
        state: absent
      with_items: "{{ harden_sysctl_distribution_remove }}"

- name: Harden sysctl config - network
  ansible.posix.sysctl:
    name: "{{ item.n }}"
    value: "{{ item.v }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items: "{{ harden_sysctl_network_settings }}"
  when:
    - not is_container

- name: Not container
  when:
    - not is_container
  block:
    - name: Debug | ansible_virtualization_type
      ansible.builtin.debug:
        var: ansible_virtualization_type
    - name: Harden sysctl config - network
      ansible.posix.sysctl:
        name: "{{ item.n }}"
        value: "{{ item.v }}"
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - { n: 'net.ipv4.tcp_rfc1337', v: 1 }
    - name: Get kernel version
      ansible.builtin.set_fact:
        kernel_r: "{{ ansible_kernel.split('-')[0] }}"
    - name: Debug | kernel release
      ansible.builtin.debug:
        var: kernel_r
    - name: Harden sysctl config - network - RFC5961 linux vuln
      ansible.posix.sysctl:
        name: "{{ item.n }}"
        value: "{{ item.v }}"
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - { n: 'net.ipv4.tcp_challenge_ack_limit', v: 999999999 }
      # when: "{{ kernel_r | version_compare('3.6', '>=') }}" and "{{ kernel_r | version_compare('4.7', '<') }}"
      when: kernel_r is version_compare('3.6', '>=')
    - name: Distribution
      when: >
        harden_sysctl_distribution is defined and harden_sysctl_distribution and
        harden_sysctl_distribution != 'None'
      block:
        - name: Debug | harden_sysctl_distribution
          ansible.builtin.debug:
            var: harden_sysctl_distribution
        - name: Harden sysctl config - distribution specific
          ansible.posix.sysctl:
            name: "{{ item.n }}"
            value: "{{ item.v }}"
            sysctl_set: yes
            state: present
            reload: yes
          with_items: "{{ harden_sysctl_distribution }}"
## Note: exclude kvm because lxc/digitalocean misidentified - ansible < v2.2
##  https://github.com/ansible/ansible/issues/17030

- name: Network forwarding disabled
  when:
    - not (harden_sysctl_use_forwarding is defined and harden_sysctl_use_forwarding)
    - not is_container
  block:
    - name: Disable forwarding in sysctl config
      ansible.posix.sysctl:
        name: "{{ item.n }}"
        value: "{{ item.v }}"
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - { n: 'net.ipv4.conf.all.forwarding', v: 0 }
        - { n: 'net.ipv4.ip_forward', v: 0 }
- name: Network forwarding enabled
  when:
    - (harden_sysctl_use_forwarding is defined and harden_sysctl_use_forwarding)
    - not is_container
  block:
    - name: Enable forwarding in sysctl config
      ansible.posix.sysctl:
        name: "{{ item.n }}"
        value: "{{ item.v }}"
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - { n: 'net.ipv4.conf.all.forwarding', v: 1 }
        - { n: 'net.ipv4.ip_forward', v: 1 }

- name: Set limited ping group range
  ansible.posix.sysctl:
    name: net.ipv4.ping_group_range
    value: "{{ harden_sysctl_ping_group_range | default('0  2147483647') }}"
    sysctl_set: yes
    sysctl_file: "{% if ansible_os_family == 'Debian' %}/etc/sysctl.d/99-allow-ping.conf{% else %}{{ omit }}{% endif %}"
    state: present
    reload: yes
  when:
    - not is_container or ansible_distribution == 'Ubuntu'

## Fedora22+: https://bugzilla.redhat.com/show_bug.cgi?id=1196825
- name: Harden sysctl config - ptrace
  ansible.posix.sysctl:
    name: "{{ item.n }}"
    value: "{{ item.v }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { n: 'kernel.yama.ptrace_scope', v: 1 }
  when: >
    not (
          is_container
          or (
            ansible_os_family == "RedHat" and
            (ansible_distribution_version.split('.')[0]|int <=7)
          ) or
          (ansible_distribution == 'Debian' and ansible_architecture != "armv6l")
        )

- name: Disable kernel modules loading completely
  ansible.posix.sysctl:
    name: "kernel.modules_disabled"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: harden_sysctl_kernel_modules_disabled_sysctl is defined and harden_sysctl_kernel_modules_disabled_sysctl

- name: After boot
  when: harden_sysctl_kernel_modules_disabled_afterboot is defined and harden_sysctl_kernel_modules_disabled_afterboot
  block:
    # - name: disable kernel modules loading now
    ### only changed value in file
    ##   ansible.posix.sysctl: name="kernel.modules_disabled" value=1 state=present
    #   ansible.posix.sysctl: name="kernel.modules_disabled" value=1 state=absent sysctl_set=yes
    #   when: >
    #     not (ansible_virtualization_type is defined and
    #          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
    #     ) or ansible_distribution == 'Ubuntu'
    - name: Disable kernel modules loading after initial boot
      ansible.builtin.template:
        src: rc.local.j2
        dest: /etc/rc.local
        mode: '0755'
        owner: root
    - name: Debian systemd
      when: ansible_service_mgr == 'systemd' and ansible_os_family == "Debian"
      block:
        - name: Ensure systemd rc-local override directory exists
          ansible.builtin.file:
            path: /etc/systemd/system/rc-local.service.d
            state: directory
            mode: '0755'
        - name: Ensure systemd rc-local has an install section
          ansible.builtin.template:
            src: systemd-rc-local.conf.j2
            dest: /etc/systemd/system/rc-local.service.d/install.conf
            mode: '0644'
        - name: Enabling rc.local with systemd
          ansible.builtin.service:
            name: rc-local
            enabled: yes
